shamefullyHoist: true
autoInstallPeers: true
ignoreWorkspaceRootCheck: true

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
  workerd: false
  better-sqlite3: false
  sharp: false
